server:
  port: 8401
spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        #服务注册中心
        server-addr: localhost:8848
    sentinel:
      transport:
        #配置Sentinel Dashboard的地址
        dashboard: localhost:8080
        #默认8719，如果端口被占用，端口会自动 +1，提供给sentinel的监控端口
        port: 8719

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    sentinel:
      enabled: true