server:
  port: 2001
spring:
  application:
    name: seate-order-service
  cloud:
    alibaba:
      seata:
        tx-service-group: fxp_tx_group
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_order
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    io:
      seata: info