server:
  port: 8093

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    register-with-eureka: false  #不注册进eureka
#    fetch-registry: true
    service-url:
      #      defaultZone: http://localhost:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

#设置超时等待时间
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

logging:
  config:
    com.atguigu.springcloud.service.PaymentFeignService: debug