server:
  port: 8004

spring:
  application:
    name: cloud-provider-service
  cloud:
    zookeeper:
      connect-string: 175.24.121.46:2181
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://175.24.121.46:3306/cloud2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: admin
    password: KooKoozei?p@e7kohceico7shood7zaes9ier;igh{oo3EPa